# Generated by Django 3.1.7 on 2021-03-22 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestClass',
            fields=[
                ('new_blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BlogPost.blogmodel')),
            ],
            bases=('BlogPost.blogmodel',),
        ),
    ]
