# Generated by Django 3.1.7 on 2021-03-22 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0002_testclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='testclass',
            name='blogmodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BlogPost.blogmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testclass',
            name='new_blog',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='BlogPost.blogmodel'),
        ),
    ]
