# Generated by Django 3.1.7 on 2021-06-05 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0002_blogcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comment', to='BlogPost.blog'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
